#!/usr/bin/env python3
"""Verify a named ortholog input list against bounded, frozen B3 score tables.

This checks arithmetic ranking origin and byte hashes; it does not establish
that the source was generated by the claimed model or that its universe is full.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.build_ortholog_table import canonical_gene_id


MIB = 1024 * 1024
TIE_RULES = {"gene_id_ascending", "include_all_at_k"}


def bounded_hash(path: Path, limit: int) -> str:
    if path.stat().st_size > limit:
        raise ValueError(f"{path}: exceeds the {limit} byte input cap")
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(MIB), b""):
            digest.update(chunk)
    return digest.hexdigest()


def bounded_json(path: Path) -> dict:
    if path.stat().st_size > MIB:
        raise ValueError(f"{path}: JSON exceeds the 1 MiB cap")
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return value


def canonical_set(species: str, genes: object, label: str) -> set[str]:
    if not isinstance(genes, list) or not genes or any(
        not isinstance(gene, str) or not gene or gene != gene.strip() for gene in genes
    ):
        raise ValueError(f"{label}: expected a nonempty array of trimmed gene IDs")
    canonical = [canonical_gene_id(species, gene) for gene in genes]
    if len(canonical) != len(set(canonical)):
        raise ValueError(f"{label}: duplicate canonical gene ID")
    return set(canonical)


def verify_side(
    *, species: str, phase: str, statistic: str, provenance: str,
    requested: set[str], stats_hash: str, scores_path: Path, metadata_path: Path,
    source_path: Path, max_score_bytes: int, max_source_bytes: int, max_rows: int,
) -> dict:
    if scores_path.resolve() == source_path.resolve():
        raise ValueError("B3 source artifact and scored table must be distinct files")
    metadata = bounded_json(metadata_path)
    expected_fields = {
        "species": species, "phase": phase, "statistic": statistic,
        "statistic_provenance": provenance,
        "statistics_source_sha256": stats_hash,
        "score_definition": "null_corrected_z",
        "selection_rule": "descending_null_corrected_z",
        "score_universe": "all_scored_genes_for_species_phase",
    }
    for key, value in expected_fields.items():
        if metadata.get(key) != value:
            raise ValueError(f"{metadata_path}: {key} must equal {value!r}")
    for key in ("run_id", "model_id", "data_id", "split_id"):
        value = metadata.get(key)
        if not isinstance(value, str) or not value or value != value.strip():
            raise ValueError(f"{metadata_path}: {key} must be a nonempty trimmed string")
    tie_rule = metadata.get("tie_rule")
    if tie_rule not in TIE_RULES:
        raise ValueError(f"{metadata_path}: unsupported tie_rule {tie_rule!r}")
    top_k = metadata.get("top_k")
    if type(top_k) is not int or top_k < 1:
        raise ValueError(f"{metadata_path}: top_k must be a positive integer")
    named_k = re.fullmatch(r"impact_top_([1-9][0-9]*)", statistic)
    if named_k is None or top_k != int(named_k.group(1)):
        raise ValueError(f"{metadata_path}: top_k must match an impact_top_N statistic")
    selected = canonical_set(species, metadata.get("selected_gene_ids"), "selected_gene_ids")
    if selected != requested:
        raise ValueError(f"{metadata_path}: selected IDs disagree with the statistic request")
    score_hash = bounded_hash(scores_path, max_score_bytes)
    source_hash = bounded_hash(source_path, max_source_bytes)
    if metadata.get("score_table_sha256") != score_hash:
        raise ValueError(f"{metadata_path}: score_table_sha256 mismatch")
    if metadata.get("b3_source_sha256") != source_hash:
        raise ValueError(f"{metadata_path}: b3_source_sha256 mismatch")

    scores: list[tuple[str, float]] = []
    seen: set[str] = set()
    with scores_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames != ["gene_id", "null_corrected_z"]:
            raise ValueError(f"{scores_path}: expected gene_id and null_corrected_z columns")
        for line, row in enumerate(reader, start=2):
            if len(scores) >= max_rows:
                raise ValueError(f"{scores_path}: exceeds the {max_rows} row cap")
            if None in row:
                raise ValueError(f"{scores_path}: extra field at line {line}")
            gene = row["gene_id"]
            if not gene or gene != gene.strip() or canonical_gene_id(species, gene) != gene:
                raise ValueError(f"{scores_path}: noncanonical gene ID at line {line}")
            if gene in seen:
                raise ValueError(f"{scores_path}: duplicate gene ID {gene}")
            seen.add(gene)
            try:
                score = float(row["null_corrected_z"])
            except (TypeError, ValueError) as exc:
                raise ValueError(f"{scores_path}: invalid score for {gene}") from exc
            if not math.isfinite(score):
                raise ValueError(f"{scores_path}: nonfinite score for {gene}")
            scores.append((gene, score))
    if len(scores) < top_k:
        raise ValueError(f"{scores_path}: fewer than top_k scored genes")
    scores.sort(key=lambda item: (-item[1], item[0]))
    cutoff = scores[top_k - 1][1]
    expected = {
        gene for gene, score in scores
        if score > cutoff or (score == cutoff and tie_rule == "include_all_at_k")
    }
    if tie_rule == "gene_id_ascending":
        expected = {gene for gene, _ in scores[:top_k]}
    if requested != expected:
        missing, extra = expected - requested, requested - expected
        raise ValueError(
            f"{species}: selected list differs from the declared top-k rule; "
            f"{len(missing)} missing (first {min(missing) if missing else 'none'}), "
            f"{len(extra)} extra (first {min(extra) if extra else 'none'})"
        )
    return {
        "species": species, "phase": phase, "statistic": statistic,
        "run_id": metadata["run_id"], "model_id": metadata["model_id"],
        "data_id": metadata["data_id"], "split_id": metadata["split_id"],
        "score_table_sha256": score_hash, "b3_source_sha256": source_hash,
        "metadata_sha256": bounded_hash(metadata_path, MIB),
        "n_scored_genes": len(scores), "n_selected": len(expected),
        "top_k": top_k, "cutoff_score": cutoff,
        "n_at_cutoff": sum(score == cutoff for _, score in scores),
        "selection_rule": metadata["selection_rule"], "tie_rule": tie_rule,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("statistics", "scores-a", "scores-b", "metadata-a", "metadata-b",
                 "b3-source-a", "b3-source-b", "output"):
        parser.add_argument(f"--{name}", required=True, type=Path)
    for name in ("species-a", "species-b", "phase", "statistic"):
        parser.add_argument(f"--{name}", required=True)
    parser.add_argument("--max-score-mib", type=int, default=64)
    parser.add_argument("--max-source-mib", type=int, default=256)
    parser.add_argument("--max-rows", type=int, default=100_000)
    args = parser.parse_args()
    if min(args.max_score_mib, args.max_source_mib, args.max_rows) < 1:
        parser.error("All input caps must be positive")
    paths = (args.statistics, args.scores_a, args.scores_b, args.metadata_a,
             args.metadata_b, args.b3_source_a, args.b3_source_b)
    if args.output.resolve() in {path.resolve() for path in paths}:
        raise ValueError("Output cannot overwrite an input")
    statistics = bounded_json(args.statistics)
    records = statistics.get("statistics")
    if not isinstance(records, list):
        raise ValueError("Statistic input requires a statistics array")
    wanted = (args.species_a, args.species_b, args.phase, args.statistic)
    matches = [item for item in records if isinstance(item, dict) and
               tuple(item.get(key) for key in ("species_a", "species_b", "phase", "statistic")) == wanted]
    if len(matches) != 1:
        raise ValueError("Expected exactly one matching statistic request")
    request = matches[0]
    provenance = request.get("provenance")
    if not isinstance(provenance, str) or not provenance or provenance != provenance.strip():
        raise ValueError("Statistic provenance must be a nonempty trimmed string")
    stats_hash = bounded_hash(args.statistics, MIB)
    sides = []
    for suffix in ("a", "b"):
        sides.append(verify_side(
            species=getattr(args, f"species_{suffix}"), phase=args.phase,
            statistic=args.statistic, provenance=provenance,
            requested=canonical_set(getattr(args, f"species_{suffix}"),
                                    request.get(f"genes_{suffix}"), f"genes_{suffix}"),
            stats_hash=stats_hash, scores_path=getattr(args, f"scores_{suffix}"),
            metadata_path=getattr(args, f"metadata_{suffix}"),
            source_path=getattr(args, f"b3_source_{suffix}"),
            max_score_bytes=args.max_score_mib * MIB,
            max_source_bytes=args.max_source_mib * MIB, max_rows=args.max_rows,
        ))
    if any(sides[0][key] != sides[1][key] for key in
           ("run_id", "model_id", "top_k", "selection_rule", "tie_rule")):
        raise ValueError("Species sides disagree on run, model or ranking rule")
    result = {
        "schema_version": 1, "status": "top_k_matches_submitted_score_tables",
        "statistics_source_sha256": stats_hash, "statistic_provenance": provenance,
        "sides": sides,
        "scope_limit": "Hashes and ranking arithmetic do not prove B3 producer identity or score-universe completeness.",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True, allow_nan=False) + "\n")


if __name__ == "__main__":
    main()
